baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "data-science"
disqusShortname = "yourdiscussshortname"
enableEmoji = true

preserveTaxonomyNames = true

# sectionPagesMenu = "main"

[permalinks]
    post = "/:year/:month/:day/:slug/"



[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[params]
  author = "Amber Thomas"

  # options for highlight.js (version, additional languages, and theme)
  highlight = true
  highlightjsVersion = "9.15.6"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml", "javascript"]
  custom = true
  highlightjsThemeLight = ""
  highlightjsThemeDark = ""





[params.social]
  email = "mailto:AmberThomasMSc@gmail.com"
  twitter = "https://twitter.com/ProQuesAsker"
  github = "https://www.github.com/ProQuestionAsker"
  linkedin = "https://www.linkedin.com/in/amberrthomas/"
  stackoverflow = ""
  facebook = ""
  instagram = ""
  dribbble = ""
  kaggle = ""
  medium = ""
  patreon = ""
  pinterest = ""
  youtube = ""